# Generated by Django 3.1.6 on 2026-02-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ride_riderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='destination_state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
