# Generated by Django 3.1.6 on 2026-02-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='max_detour_minutes',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='ride',
            name='route_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='route_polyline',
            field=models.TextField(blank=True, default=''),
        ),
    ]
