# Generated by Django 3.1.6 on 2026-02-22 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0006_auto_20260214_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('custom', 'Custom')], max_length=8)),
                ('label', models.CharField(blank=True, max_length=64)),
                ('address', models.CharField(blank=True, default='', max_length=256)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
