# Generated by Django 3.1.6 on 2026-02-27 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0007_favoritelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('did_not_show_up', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('flagged', models.BooleanField(default=False)),
                ('ratee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='rides.ride')),
                ('ride_request', models.ForeignKey(help_text='Links rater/ratee for this ride (driver-rider pair)', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='rides.riderequest')),
            ],
            options={
                'unique_together': {('rater', 'ride_request')},
            },
        ),
    ]
